# -*- coding: utf-8 -*-
# Copyright (c) Meta Platforms, Inc. and affiliates.
# Modified by XuDong Wang from https://github.com/facebookresearch/Mask2Former/tree/main/mask2former_video

from detectron2.config import CfgNode as CN


def add_maskformer2_video_config(cfg):
    # video data
    # DataLoader
    cfg.INPUT.SAMPLING_FRAME_NUM = 2
    cfg.INPUT.SAMPLING_FRAME_RANGE = 20
    cfg.INPUT.SAMPLING_FRAME_SHUFFLE = False
    cfg.INPUT.AUGMENTATIONS = [] # "brightness", "contrast", "saturation", "rotation"

    cfg.MODEL.MASK_FORMER.LOSS_STRATEGY = "full"

    cfg.DATALOADER.COPY_PASTE = False
    cfg.DATALOADER.COPY_PASTE_RATE = 0.0
    cfg.DATALOADER.COPY_PASTE_MIN_RATIO = 0.5
    cfg.DATALOADER.COPY_PASTE_MAX_RATIO = 1.0
    cfg.DATALOADER.COPY_PASTE_RANDOM_NUM = True # random select number of instances
    cfg.DATALOADER.VISUALIZE_COPY_PASTE = False
    cfg.DATALOADER.COPY_PASTE_DENSIFY_SPARSE = False

    cfg.SOLVER.BASE_LR_MULTIPLIER = 1
    cfg.SOLVER.BASE_LR_MULTIPLIER_NAMES = []

    cfg.MODEL.MASK_FORMER.TEST.USE_NMS = False
    cfg.MODEL.MASK_FORMER.TEST.NMS_THRESH = 0.6
    cfg.MODEL.MASK_FORMER.TEST.NUM_PREDICTIONS = 10

    cfg.MODEL.MASK_FORMER.EMA_MOMENTUM = 0.999
    cfg.MODEL.MASK_FORMER.EMA_MOMENTUM_SCHEDULE = False
    cfg.MODEL.MASK_FORMER.EMA_MOMENTUM_END = 0.999
    cfg.MODEL.MASK_FORMER.EMA_MOMENTUM_UNTIL_STEP = 10000

    cfg.MODEL.MASK_FORMER.NUM_PREDICTIONS_DISTILLATION = 100
    cfg.MODEL.MASK_FORMER.SCORE_THRESHOLD_DISTILLATION = 0.75

    cfg.MODEL.MASK_FORMER.KD_CLASS_WEIGHT = 0.0
    cfg.MODEL.MASK_FORMER.KD_MASK_WEIGHT = 5.0
    cfg.MODEL.MASK_FORMER.KD_DICE_WEIGHT = 5.0
    cfg.MODEL.MASK_FORMER.LOSS_WEIGHT_DECAY_STEP = 0.0
    cfg.MODEL.MASK_FORMER.KD_WEIGHT_SCHEDULER = "constant" # "linear", "constant", "cosine"
    cfg.MODEL.MASK_FORMER.DECAY_ONLY_SUPERVISED_LOSS = False
    cfg.MODEL.MASK_FORMER.DECAY_ONLY_KD_LOSS = False
    cfg.MODEL.MASK_FORMER.SUPERVISED_MIN_WEIGHT = 0.0
    cfg.MODEL.MASK_FORMER.KD_MIN_WEIGHT = 0.0
    cfg.MODEL.MASK_FORMER.KD_WEIGHT_DECAY_START = 0.0
    cfg.MODEL.MASK_FORMER.KD_WEIGHT_DECAY_END = -1.0

    cfg.MODEL.MASK_FORMER.DETACH_CLS = False

    cfg.MODEL.MASK_FORMER.SPARSE_CLASS_WEIGHT = 0.0
    cfg.MODEL.MASK_FORMER.ENTROPY_WEIGHT = 0.0
    cfg.MODEL.MASK_FORMER.MASK_DROPLOSS = False
    cfg.MODEL.MASK_FORMER.LABEL_DROPLOSS = False
    cfg.MODEL.MASK_FORMER.NO_CLASS_MATCH = False

    cfg.MODEL.MASK_FORMER.DISTILLATION_NMS = False
    cfg.MODEL.MASK_FORMER.DISTILLATION_LOSS_STRATEGY = "masks-only"
    cfg.MODEL.MASK_FORMER.TEST.EVAL_STUDENT = False

    cfg.SOLVER.ACCUM_ITER = 1

    cfg.INPUT.DENSE_ANNOTATION_SELECTION = True
    cfg.INPUT.DISENTANGLE_DISTILLATION_LOADER = False
    cfg.INPUT.DISTILLATION_DENSE_ANNOTATION_SELECTION = True

    cfg.MODEL.WEIGHT_LIST = []

